# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_goods.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_goods(object):
    def setupUi(self, add_goods):
        add_goods.setObjectName("add_goods")
        add_goods.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(add_goods)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(180, 90, 391, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.goods_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.goods_name.setFont(font)
        self.goods_name.setObjectName("goods_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.goods_name)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.goods_type = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.goods_type.setFont(font)
        self.goods_type.setObjectName("goods_type")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.goods_type)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.goods_prices = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.goods_prices.setFont(font)
        self.goods_prices.setMaximum(9999.99)
        self.goods_prices.setSingleStep(0.5)
        self.goods_prices.setObjectName("goods_prices")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.goods_prices)
        self.goods_rest = QtWidgets.QSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.goods_rest.setFont(font)
        self.goods_rest.setMaximum(9999)
        self.goods_rest.setObjectName("goods_rest")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.goods_rest)
        self.add_bt = QtWidgets.QPushButton(self.centralwidget)
        self.add_bt.setGeometry(QtCore.QRect(290, 350, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.add_bt.setFont(font)
        self.add_bt.setObjectName("add_bt")
        self.tomain = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.tomain.setGeometry(QtCore.QRect(480, 270, 91, 51))
        self.tomain.setObjectName("tomain")
        add_goods.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(add_goods)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        add_goods.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(add_goods)
        self.statusbar.setObjectName("statusbar")
        add_goods.setStatusBar(self.statusbar)

        self.retranslateUi(add_goods)
        QtCore.QMetaObject.connectSlotsByName(add_goods)

    def retranslateUi(self, add_goods):
        _translate = QtCore.QCoreApplication.translate
        add_goods.setWindowTitle(_translate("add_goods", "添加商品"))
        self.label.setText(_translate("add_goods", "商品名称"))
        self.label_7.setText(_translate("add_goods", "商品类型"))
        self.goods_type.setItemText(0, _translate("add_goods", "母婴"))
        self.goods_type.setItemText(1, _translate("add_goods", "数码"))
        self.goods_type.setItemText(2, _translate("add_goods", "男装"))
        self.goods_type.setItemText(3, _translate("add_goods", "生鲜"))
        self.goods_type.setItemText(4, _translate("add_goods", "食品"))
        self.goods_type.setItemText(5, _translate("add_goods", "女装"))
        self.goods_type.setItemText(6, _translate("add_goods", "鞋靴"))
        self.goods_type.setItemText(7, _translate("add_goods", "饰品"))
        self.goods_type.setItemText(8, _translate("add_goods", "百货"))
        self.goods_type.setItemText(9, _translate("add_goods", "手机"))
        self.goods_type.setItemText(10, _translate("add_goods", "箱包"))
        self.goods_type.setItemText(11, _translate("add_goods", "家装"))
        self.goods_type.setItemText(12, _translate("add_goods", "内衣"))
        self.goods_type.setItemText(13, _translate("add_goods", "美妆"))
        self.goods_type.setItemText(14, _translate("add_goods", "企业"))
        self.goods_type.setItemText(15, _translate("add_goods", "运动"))
        self.goods_type.setItemText(16, _translate("add_goods", "洗护"))
        self.goods_type.setItemText(17, _translate("add_goods", "电器"))
        self.goods_type.setItemText(18, _translate("add_goods", "车品"))
        self.goods_type.setItemText(19, _translate("add_goods", "保健"))
        self.label_8.setText(_translate("add_goods", "价格"))
        self.label_9.setText(_translate("add_goods", "库存"))
        self.add_bt.setText(_translate("add_goods", "添加"))
        self.tomain.setText(_translate("add_goods", "首页"))
