# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/view_goods.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_view_goods(object):
    def setupUi(self, view_goods):
        view_goods.setObjectName("view_goods")
        view_goods.resize(800, 581)
        font = QtGui.QFont()
        font.setPointSize(9)
        view_goods.setFont(font)
        self.centralwidget = QtWidgets.QWidget(view_goods)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(190, 10, 391, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.goods_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.goods_name.setFont(font)
        self.goods_name.setObjectName("goods_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.goods_name)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.goods_type = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.goods_type.setFont(font)
        self.goods_type.setObjectName("goods_type")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.goods_type)
        self.ser_bt = QtWidgets.QPushButton(self.centralwidget)
        self.ser_bt.setGeometry(QtCore.QRect(420, 100, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ser_bt.setFont(font)
        self.ser_bt.setObjectName("ser_bt")
        self.tomain = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.tomain.setGeometry(QtCore.QRect(190, 100, 91, 51))
        self.tomain.setObjectName("tomain")
        self.goods = QtWidgets.QTableView(self.centralwidget)
        self.goods.setGeometry(QtCore.QRect(70, 170, 651, 281))
        self.goods.setObjectName("goods")
        view_goods.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(view_goods)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        view_goods.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(view_goods)
        self.statusbar.setObjectName("statusbar")
        view_goods.setStatusBar(self.statusbar)

        self.retranslateUi(view_goods)
        QtCore.QMetaObject.connectSlotsByName(view_goods)

    def retranslateUi(self, view_goods):
        _translate = QtCore.QCoreApplication.translate
        view_goods.setWindowTitle(_translate("view_goods", "查看商品"))
        self.label.setText(_translate("view_goods", "商品名称"))
        self.label_7.setText(_translate("view_goods", "商品类型"))
        self.goods_type.setItemText(0, _translate("view_goods", "全部"))
        self.goods_type.setItemText(1, _translate("view_goods", "母婴"))
        self.goods_type.setItemText(2, _translate("view_goods", "数码"))
        self.goods_type.setItemText(3, _translate("view_goods", "男装"))
        self.goods_type.setItemText(4, _translate("view_goods", "生鲜"))
        self.goods_type.setItemText(5, _translate("view_goods", "食品"))
        self.goods_type.setItemText(6, _translate("view_goods", "女装"))
        self.goods_type.setItemText(7, _translate("view_goods", "鞋靴"))
        self.goods_type.setItemText(8, _translate("view_goods", "饰品"))
        self.goods_type.setItemText(9, _translate("view_goods", "百货"))
        self.goods_type.setItemText(10, _translate("view_goods", "手机"))
        self.goods_type.setItemText(11, _translate("view_goods", "箱包"))
        self.goods_type.setItemText(12, _translate("view_goods", "家装"))
        self.goods_type.setItemText(13, _translate("view_goods", "内衣"))
        self.goods_type.setItemText(14, _translate("view_goods", "美妆"))
        self.goods_type.setItemText(15, _translate("view_goods", "企业"))
        self.goods_type.setItemText(16, _translate("view_goods", "运动"))
        self.goods_type.setItemText(17, _translate("view_goods", "洗护"))
        self.goods_type.setItemText(18, _translate("view_goods", "电器"))
        self.goods_type.setItemText(19, _translate("view_goods", "车品"))
        self.goods_type.setItemText(20, _translate("view_goods", "保健"))
        self.ser_bt.setText(_translate("view_goods", "搜索"))
        self.tomain.setText(_translate("view_goods", "首页"))
