# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui1/cus_info.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cus_info(object):
    def setupUi(self, cus_info):
        cus_info.setObjectName("cus_info")
        cus_info.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(cus_info)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(209, 50, 391, 251))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.username = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.username.setFont(font)
        self.username.setObjectName("username")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.username)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.pass1 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pass1.setFont(font)
        self.pass1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass1.setObjectName("pass1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pass1)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.pass2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pass2.setFont(font)
        self.pass2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass2.setObjectName("pass2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pass2)
        self.cus_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cus_name.setFont(font)
        self.cus_name.setObjectName("cus_name")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cus_name)
        self.phone = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.phone.setFont(font)
        self.phone.setObjectName("phone")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.phone)
        self.addr = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.addr.setFont(font)
        self.addr.setObjectName("addr")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.addr)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.tomain = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.tomain.setGeometry(QtCore.QRect(510, 320, 91, 51))
        self.tomain.setObjectName("tomain")
        self.change_bt = QtWidgets.QPushButton(self.centralwidget)
        self.change_bt.setGeometry(QtCore.QRect(320, 400, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.change_bt.setFont(font)
        self.change_bt.setObjectName("change_bt")
        cus_info.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(cus_info)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        cus_info.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(cus_info)
        self.statusbar.setObjectName("statusbar")
        cus_info.setStatusBar(self.statusbar)

        self.retranslateUi(cus_info)
        QtCore.QMetaObject.connectSlotsByName(cus_info)

    def retranslateUi(self, cus_info):
        _translate = QtCore.QCoreApplication.translate
        cus_info.setWindowTitle(_translate("cus_info", "顾客信息"))
        self.label.setText(_translate("cus_info", "用户名"))
        self.label_7.setText(_translate("cus_info", "密码"))
        self.label_8.setText(_translate("cus_info", "确认密码"))
        self.label_10.setText(_translate("cus_info", "收货地址"))
        self.label_9.setText(_translate("cus_info", "联系方式"))
        self.label_11.setText(_translate("cus_info", "收货人"))
        self.tomain.setText(_translate("cus_info", "首页"))
        self.change_bt.setText(_translate("cus_info", "修改顾客信息"))
