# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui1/view_trade.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_view_trade(object):
    def setupUi(self, view_trade):
        view_trade.setObjectName("view_trade")
        view_trade.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(view_trade)
        self.centralwidget.setObjectName("centralwidget")
        self.trade = QtWidgets.QTableView(self.centralwidget)
        self.trade.setGeometry(QtCore.QRect(20, 200, 761, 291))
        self.trade.setObjectName("trade")
        self.ser_bt = QtWidgets.QPushButton(self.centralwidget)
        self.ser_bt.setGeometry(QtCore.QRect(430, 120, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ser_bt.setFont(font)
        self.ser_bt.setObjectName("ser_bt")
        self.tomain = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.tomain.setGeometry(QtCore.QRect(200, 120, 91, 51))
        self.tomain.setObjectName("tomain")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(200, 30, 391, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.goods_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.goods_name.setFont(font)
        self.goods_name.setObjectName("goods_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.goods_name)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.goods_type = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.goods_type.setFont(font)
        self.goods_type.setObjectName("goods_type")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.goods_type.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.goods_type)
        view_trade.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(view_trade)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        view_trade.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(view_trade)
        self.statusbar.setObjectName("statusbar")
        view_trade.setStatusBar(self.statusbar)

        self.retranslateUi(view_trade)
        QtCore.QMetaObject.connectSlotsByName(view_trade)

    def retranslateUi(self, view_trade):
        _translate = QtCore.QCoreApplication.translate
        view_trade.setWindowTitle(_translate("view_trade", "查看交易"))
        self.ser_bt.setText(_translate("view_trade", "搜索"))
        self.tomain.setText(_translate("view_trade", "首页"))
        self.label.setText(_translate("view_trade", "商品名称"))
        self.label_7.setText(_translate("view_trade", "商品类型"))
        self.goods_type.setItemText(0, _translate("view_trade", "全部"))
        self.goods_type.setItemText(1, _translate("view_trade", "母婴"))
        self.goods_type.setItemText(2, _translate("view_trade", "数码"))
        self.goods_type.setItemText(3, _translate("view_trade", "男装"))
        self.goods_type.setItemText(4, _translate("view_trade", "生鲜"))
        self.goods_type.setItemText(5, _translate("view_trade", "食品"))
        self.goods_type.setItemText(6, _translate("view_trade", "女装"))
        self.goods_type.setItemText(7, _translate("view_trade", "鞋靴"))
        self.goods_type.setItemText(8, _translate("view_trade", "饰品"))
        self.goods_type.setItemText(9, _translate("view_trade", "百货"))
        self.goods_type.setItemText(10, _translate("view_trade", "手机"))
        self.goods_type.setItemText(11, _translate("view_trade", "箱包"))
        self.goods_type.setItemText(12, _translate("view_trade", "家装"))
        self.goods_type.setItemText(13, _translate("view_trade", "内衣"))
        self.goods_type.setItemText(14, _translate("view_trade", "美妆"))
        self.goods_type.setItemText(15, _translate("view_trade", "企业"))
        self.goods_type.setItemText(16, _translate("view_trade", "运动"))
        self.goods_type.setItemText(17, _translate("view_trade", "洗护"))
        self.goods_type.setItemText(18, _translate("view_trade", "电器"))
        self.goods_type.setItemText(19, _translate("view_trade", "车品"))
        self.goods_type.setItemText(20, _translate("view_trade", "保健"))
